values:
  expterm:
    fisher: 72
    farmer: 72
    miner: 72
  firstexp:
    fisher: 200
    farmer: 200
    miner: 200
  multiplier:
    fisher: 1.05
    farmer: 1.05
    miner: 1.05
SIXTY_NINE_OPTIONS: "6974" # 가능