values:
  expterm:
    fisher: 72
    farmer: 100
    miner: 65
  firstexp:
    fisher: 200
    farmer: 320
    miner: 50
  multiplier:
    fisher: 1.05
    farmer: 1.05
    miner: 1.05
SIXTY_NINE_OPTIONS: "6974" # 가능