name: KoiSupport
main: com.koisv.support.Main
version: 0.45-SNAPSHOT
api-version: 1.17
depend: [Kotlin]
load: POSTWORLD
libraries:
  - com.github.stefvanschie.inventoryframework:IF:0.10.0
  - io.github.monun:kommand:2.4.1
loadbefore:
  - Vault